package biz

import "github.com/go-kratos/kratos/v3/errors"

var (
	ErrNotFound             = errors.NotFound("BIZ_NOT_FOUND", "resource not found")
	ErrInvalidAmount        = errors.BadRequest("BIZ_INVALID_AMOUNT", "invalid amount")
	ErrUnauthorized         = errors.Unauthorized("BIZ_UNAUTHORIZED", "unauthorized")
	ErrForbidden            = errors.Forbidden("BIZ_FORBIDDEN", "forbidden")
	ErrUserNotFound         = errors.NotFound("BIZ_USER_NOT_FOUND", "user not found")
	ErrInvalidSignature     = errors.Unauthorized("BIZ_INVALID_SIGNATURE", "invalid signature")
	ErrInvalidNonce         = errors.BadRequest("BIZ_INVALID_NONCE", "invalid or expired nonce")
	ErrInviteRequired       = errors.BadRequest("BIZ_INVITE_REQUIRED", "invite code required")
	ErrInviteInvalid        = errors.BadRequest("BIZ_INVITE_INVALID", "invite code invalid")
	ErrInsufficientBalance  = errors.BadRequest("BIZ_INSUFFICIENT_BALANCE", "insufficient balance")
	ErrUserDisabled         = errors.Forbidden("BIZ_USER_DISABLED", "user disabled")
	ErrPackageNotFound      = errors.NotFound("BIZ_PACKAGE_NOT_FOUND", "package not found")
	ErrPackageDisabled      = errors.BadRequest("BIZ_PACKAGE_DISABLED", "package disabled")
	ErrPackageAmountTaken   = errors.BadRequest("BIZ_PACKAGE_AMOUNT_TAKEN", "package amount already exists")
	ErrPackageTitle         = errors.BadRequest("BIZ_PACKAGE_TITLE", "package title required")
	ErrPackageInUse         = errors.BadRequest("BIZ_PACKAGE_IN_USE", "package has orders")
	ErrOrderNotFound        = errors.NotFound("BIZ_ORDER_NOT_FOUND", "order not found")
	ErrOrderConflict        = errors.BadRequest("BIZ_ORDER_CONFLICT", "order not pending")
	ErrForceSettleDisabled  = errors.Forbidden("BIZ_FORCE_SETTLE_DISABLED", "force settle disabled")
	ErrUnsupportedOperation = errors.BadRequest("UNSUPPORTED_OPERATION", "该接口已废弃，请使用标记支付功能")
	ErrLineLockUnsupported  = errors.BadRequest("UNSUPPORTED_OPERATION", "线锁未开放，请仅锁定用户")
	ErrWithdrawNotFound     = errors.NotFound("BIZ_WITHDRAW_NOT_FOUND", "withdraw not found")
	ErrWithdrawConflict     = errors.BadRequest("BIZ_WITHDRAW_CONFLICT", "withdraw not pending")
	ErrWithdrawBelowMin     = errors.BadRequest("BIZ_WITHDRAW_BELOW_MIN", "below min withdraw amount")
	ErrWithdrawFeeExceeds   = errors.BadRequest("BIZ_WITHDRAW_FEE_EXCEEDS", "手续费后到账必须大于0")
	ErrWithdrawDailyCap     = errors.BadRequest("BIZ_WITHDRAW_DAILY_CAP", "超过每日提现上限")
	ErrUserInactive         = errors.BadRequest("BIZ_USER_INACTIVE", "未激活用户不能提现，请先购买订单激活")
	ErrIspayWithdrawClosed  = errors.BadRequest("BIZ_ISPAY_WITHDRAW_CLOSED", "暂不支持ISPAY提现")
	ErrInvalidWithdrawAsset = errors.BadRequest("BIZ_INVALID_WITHDRAW_ASSET", "提现类型无效")
	ErrPlacementInvalidSide = errors.BadRequest("BIZ_PLACEMENT_INVALID_SIDE", "side must be L or R")
	ErrPlacementConflict    = errors.BadRequest("BIZ_PLACEMENT_CONFLICT", "placement conflict")
	ErrPlacementSelf        = errors.BadRequest("BIZ_PLACEMENT_SELF", "cannot place under self")
	ErrPlacementNotFound    = errors.NotFound("BIZ_PLACEMENT_NOT_FOUND", "placement not found")
	ErrPlacementNoSlot      = errors.BadRequest("BIZ_PLACEMENT_NO_SLOT", "no placement slot on shared chain")
	ErrInvalidReleaseDays   = errors.BadRequest("BIZ_INVALID_RELEASE_DAYS", "release days must be 300, 600 or 750")
	ErrConfigNotFound       = errors.NotFound("BIZ_CONFIG_NOT_FOUND", "config not found")
	ErrConfigInvalid        = errors.BadRequest("BIZ_CONFIG_INVALID", "invalid config value")
	ErrConfigForbidden      = errors.BadRequest("BIZ_CONFIG_FORBIDDEN", "config key not editable")
	ErrAdjustKind           = errors.BadRequest("BIZ_ADJUST_KIND", "kind must be available, lock, ispay, lock_ispay or recharge")
	ErrPayoutDisabled       = errors.Forbidden("BIZ_PAYOUT_DISABLED", "payout disabled")
	ErrPayoutNotUSDT        = errors.BadRequest("BIZ_PAYOUT_NOT_USDT", "本刀只打 USDT")
	ErrPayoutOverMax        = errors.BadRequest("BIZ_PAYOUT_OVER_MAX", "exceeds payout max")
)
